### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by bach-zouk** [alexanderbaumann99/S3M#1]
Hi,

Thank you for uploading the reproducibility section for thyroid. Is there  a similar link to heart dataset? 

thank you

**Comment by alexanderbaumann99** [comment]
Hi,

thanks for your interest on our work.

The heart dataset and more information can be found here: 
https://zmiclab.github.io/zxh/0/mmwhs/2013_left_atrium_seg_challenge_mr30.zip.

Best,
Alex

**Comment by bach-zouk** [comment]
thank you for your quick response. I used nii2mesh to convert these files to ply/off format. While the training goes fine, I get NaN error during inference (when this func. is called p2p_yx = knn_query(emb1, emb2, k=1, n_jobs=n_jobs))..from FM_to_p2p. Could you please upload the ply/off/obj files. that might help to debug it. many thanks

**Comment by alexanderbaumann99** [comment]
Yes of course.
Under the following drive link, you can find the manually labelled thyroid dataset and the heart dataset (composition 3, whole heart).
https://drive.google.com/drive/folders/1k7VaHS1FrdyDo6b6jiK8Q3XBqJeMBYqt?usp=sharing
