### ISSUE TITLE
Reproducibility issues

### ISSUE THREAD

**Issue by RoelHuysentruyt** [alexanderbaumann99/S3M#3]
Hi there,

I really appreciate the concepts behind your work. However, I'm having trouble replicating the results. I've executed the code on three different datasets, including the manually labeled thyroid dataset, the heart dataset, and our in-house calcaneum dataset. Initially, I suspected issues with configuring the training settings, but even when using the provided config file for the thyroid dataset, I'm encountering problems.

None of the datasets seem to show correspondence in the corres_verts.npy or .mat files using the "y2x_pmf" key. To investigate further, I checked the mean shapes of the Statistical Shape Models (SSMs) generated by the run_evaluation file. Surprisingly, the mean shapes consistently resemble what appears to be a random point cloud, as shown below for the thyroid dataset:

Example of the mean shape obtained using the thyroid dataset:
![image](https://github.com/alexanderbaumann99/S3M/assets/114904356/f33f3bdf-1f3d-4eaf-8f7e-e85a3089fd25)

This suggests a lack of correspondence. I'm curious if you have any insights into what might be going wrong or if similar issues have been encountered before.

Thanks in advance,
Roel

**Comment by alexanderbaumann99** [comment]
Hi,
thanks for your interest in our work ! 

Are you using the most recent version of the repository? I did a commit on Jan 19, where I fixed a bug. 

Best,
Alex

**Comment by RoelHuysentruyt** [comment]
Hi Alex,

You were correct; I had been using the version uploaded prior to Jan 19. I've now tried the most recent one, and it appears to be functioning properly with all tested datasets.

Thank you for making this version available. I look forward to further exploring its potential!

Roel
